# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  decrypt-large-secrets:
    name: Decrypt Large Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: sh ./.github/scripts/decrypt_secret.sh
        env:
        LARGE_SECRET_PASSWORD: ${{ secrets.LARGE_SECRET_PASSWORD}}
      - name: Test Print
        run: cat ./app/google-services.json

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt large secret
      run: sh ./.github/scripts/decrypt_secret.sh
      env:
      LARGE_SECRET_PASSWORD: ${{ secrets.LARGE_SECRET_PASSWORD}}
    - name: Test Print
      run: cat ./app/google-services.json
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
